BackUpTwitterApp/BackUpSystem.Web/Controllers/DownloadedTweetsController.cs
using BackUpSystem.Data.Models;
using BackUpSystem.DTO;
using BackUpSystem.DTO.ApiDtos;
using BackUpSystem.Utilities.Contracts;
using BackUpSystem.Web.Models.HomeViewModels;
using BackUpSystem.Services.Data.Contracts;
using Bytes2you.Validation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Linq;

namespace BackUpSystem.Web.Controllers
{
    [Authorize]
    public class DownloadedTweetsController : Controller
    {
        private readonly IUserService userService;
        private readonly UserManager<User> userManager;
        private readonly IMappingProvider mappingProvider;

        public DownloadedTweetsController(IUserService userService, UserManager<User> userManager, IMappingProvider mappingProvider)
        {
            Guard.WhenArgument(userService, "User Service").IsNull().Throw();
            Guard.WhenArgument(userManager, "User Manager").IsNull().Throw();
            Guard.WhenArgument(mappingProvider, "Mapping Provider").IsNull().Throw();

            this.userService = userService;
            this.userManager = userManager;
            this.mappingProvider = mappingProvider;
        }

        [ResponseCache(Duration = 300)]
        public async Task<IActionResult> Index()
        {
            var model = new TimelineViewModel();
            var userId = this.userManager.GetUserId(HttpContext.User);
            var tweets = await this.userService.GetAllDownloadTweetsByUser(userId);

            var downloadedTweets = this.mappingProvider.ProjectTo<TweetApiDto, TweetViewModel>(tweets).ToList();

            for (int i = 0; i < downloadedTweets.Count(); i++)
            {
                downloadedTweets[i].CanBeDeleted = true;
            }

            model.Tweets = downloadedTweets;

            return View(model);
        }
    }
}

BackUpTwitterApp/BackUpSystem.Web/ViewComponents/FavoriteTwitterAccountsViewComponent.cs
using BackUpSystem.Data.Models;
using BackUpSystem.DTO;
using BackUpSystem.Services.Data.Contracts;
using BackUpSystem.Utilities.Contracts;
using BackUpSystem.Web.Models.HomeViewModels;
using Bytes2you.Validation;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BackUpSystem.Web.ViewComponents
{
    public class FavoriteTwitterAccountsViewComponent : ViewComponent
    {
        private readonly IUserService userService;
        private readonly IMappingProvider mappingProvider;
        private readonly UserManager<User> userManager;

        public FavoriteTwitterAccountsViewComponent(
            IUserService userService,
            IMappingProvider mappingProvider, 
            UserManager<User> userManager)
        {
            Guard.WhenArgument(userService, "User Service can not be null!").IsNull().Throw();
            Guard.WhenArgument(mappingProvider, "Mapping Provider can not be null!").IsNull().Throw();
            Guard.WhenArgument(userManager, "User Manager can not be null!").IsNull().Throw();

            this.userService = userService;
            this.mappingProvider = mappingProvider;
            this.userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new FavoriteTwitterAccountsViewModel();
            var userId = this.userManager.GetUserId(this.HttpContext.User);
            var favoriteTwitterAccounts = await userService.GetAllFavoriteTwitterAccounts(userId);

            model.TwitterAccounts = this.mappingProvider.ProjectTo<TwitterAccountDto, TwitterAccountViewModel>(favoriteTwitterAccounts);

            return View(model);
        }
    }
}

BackUpTwitterApp/BackUpSystem.Web/ViewComponents/UserProfileViewComponent.cs
using BackUpSystem.Data.Models;
using BackUpSystem.Utilities.Contracts;
using BackUpSystem.Web.Models.HomeViewModels;
using BackUpSystem.Services.Data.Contracts;
using Bytes2you.Validation;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BackUpSystem.Web.ViewComponents
{
    public class UserProfileViewComponent : ViewComponent
    {
        private readonly IUserService userService;
        private readonly IMappingProvider mappingProvider;
        private readonly UserManager<User> userManager;

        public UserProfileViewComponent(IUserService userService, IMappingProvider mappingProvider, UserManager<User> userManager)
        {
            Guard.WhenArgument(userService, "User Service can not be null!").IsNull().Throw();
            Guard.WhenArgument(mappingProvider, "Mapping Provider can not be null!").IsNull().Throw();
            Guard.WhenArgument(userManager, "User Manager can not be null!").IsNull().Throw();

            this.userService = userService;
            this.mappingProvider = mappingProvider;
            this.userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new UserProfileViewModel();
            var userId = this.userManager.GetUserId(this.HttpContext.User);
            var user = await userService.GetUserById(userId);

            model = this.mappingProvider.MapTo<UserProfileViewModel>(user);

            return View(model);
        }
    }
}

BackUpTwitterApp/BackUpSystem.Web/Views/Shared/_FooterPartial.cshtml
<!-- Footer -->
<section id="footer">
    <div class="container">
        <div class="row text-center text-xs-center text-sm-left text-md-left">
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
                <ul class="list-unstyled list-inline social text-center">
                    <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-facebook"></i></a></li>
                    <li class="list-inline-item"><a href="javascript:void();"><i class="fa fa-twitter"></i></a></li>
                    <li class="list-inline-item"><a href="javascript:void();" target="_blank"><i class="fa fa-envelope"></i></a></li>
                </ul>
            </div>
            </hr>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                <p>National Transaction Corporation is a Registered MSP/ISO of Elavon, Inc. Georgia [a wholly owned subsidiary of U.S. Bancorp, Minneapolis, MN]</p>
                <p class="h6">&copy All right Reversed.<a class="text-green ml-2" href="https://www.sunlimetech.com" target="_blank">Sunlimetech</a></p>
            </div>
            </hr>
        </div>
    </div>
</section>
<!-- ./Footer -->

BackUpTwitterApp/BackUpSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="https://abs.twimg.com/favicons/favicon.ico" />
    <title>Twitter2.0</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/sidebar.css" />
        <link rel="stylesheet" href="~/css/User-profile-card.css" />
        <link rel="stylesheet" href="~/css/tw-acc.css" />
        <link rel="stylesheet" href="~/css/search.css" />
        <link rel="stylesheet" href="~/css/authentication.min.css" />
        <link rel="stylesheet" href="~/css/footer.css" />
        <link rel="stylesheet" href="~/css/landing-page.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/sidebar.css" />
        <link rel="stylesheet" href="~/css/User-profile-card.css" />
        <link rel="stylesheet" href="~/css/tw-acc.css" />
        <link rel="stylesheet" href="~/css/search.css" />
        <link rel="stylesheet" href="~/css/authentication.min.css" />
        <link rel="stylesheet" href="~/css/footer.css" />
        <link rel="stylesheet" href="~/css/landing-page.css" />
    </environment>

    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.min.css" />
</head>
<body>
    <div class="pageContentWrapper">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container navbar-width">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Twitter2.0</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li><a asp-area="" asp-controller="DownloadedTweets" asp-action="Index">Downloaded Tweets</a></li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Admin
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Statistics" asp-action="Index">Statistics</a><hr />
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="UserManagement" asp-action="Index">User Management</a>
                                </div>
                            </li>
                        }
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About us</a></li>
                    </ul>
                    <div id="navbar" class="navbar-collapse collapse">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <div class="top-search">

                                @using (Html.BeginForm("Search", "Home", FormMethod.Post, new { @class = "navbar-form navbar-left" }))
                                {
                                    @Html.AntiForgeryToken();
                                    <input type="text" name="UserInput" class="form-control" placeholder="Search Twitter Accounts">
                                    <input type="submit" value="Go!">
                                }
                            </div>
                        }
                        @await Html.PartialAsync("_LoginPartial")
                    </div>
                </div>
            </div>
        </nav>
        <div class="wrapper">
            @if (User.Identity.IsAuthenticated)
            {
                <!-- Sidebar Holder -->
                <nav id="sidebar" style="z-index: 100;overflow-x: hidden;">
                    <div class="sidebar-header" id="user-profile">
                        @await Component.InvokeAsync("UserProfile")
                    </div>
                    <div id="fav-users">
                        @await Component.InvokeAsync("FavoriteTwitterAccounts")
                    </div>

                </nav>

            }
            <!-- Page Content Holder -->
            <div class="container  body-content">
                @RenderBody()
                <hr />
            </div>
        </div>
    </div>
    @*<footer>
            @await Html.PartialAsync("_FooterPartial")
        </footer>*@
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        <!-- Add icon library -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

BackUpTwitterApp/BackUpSystem.Web/Views/Shared/_SearchPartial.cshtml
@using BackUpSystem.Web.Models.SearchViewModels
@model SearchResultViewModel
<div class="col-lg-12 col-lg-offset-0 col-xs-8 col-xs-offset-3 p-0 ">
    @foreach (var twitterAccount in Model.SearchResult)
    {

        var backgroundImage = twitterAccount.BackgroundImage;
        <div class="col-md-8 col-md-offset-2 search-acc-banner p-0" style="background-image:url(@backgroundImage); height: 200px; background-repeat: no-repeat; background-size: cover; margin-top: 7%;">

            <div class="panel panel-default search-panel p-0" style="width:100%; background-color: white;">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="col-md-5 col-md-offset-1">
                            <h4>@twitterAccount.Name</h4>
                        </div>
                        <div class="col-md-2 ">
                            <p class="tw-color">Followers</p>
                            <p class="tw-color">@twitterAccount.FollowersCount</p>
                        </div>
                        <div class="col-md-2">
                            <p class="tw-color">Following</p>
                            <p class="tw-color">@twitterAccount.FollowingCount</p>
                        </div>
                        <div class="col-md-2">
                            <p class="tw-color">Tweets</p>
                            <p class="tw-color">@twitterAccount.TweetsCount</p>
                        </div>
                    </div>
                </div>

                @*<strong>Name: @twitterAccount.Name</strong>
                    <div>Followers: @twitterAccount.FollowersCount</div>*@

                @{
                    var messageId = $"message-{twitterAccount.Id}";
                    var visibilityFollow = "hidden";
                    var visibilityUnfollow = "hidden";

                    var followBtnId = $"follow-{twitterAccount.Id}";
                    var unfollowBtnId = $"unfollow-{twitterAccount.Id}";

                    if (!twitterAccount.IsInFavorites)
                    {
                        visibilityFollow = "visible";
                    }
                    else
                    {
                        visibilityUnfollow = "visible";
                    }
                }
                <button class="btn follow-btn btn-primary" id="@followBtnId" style="visibility: @visibilityFollow;"
                        parameter1="@twitterAccount.Id"
                        parameter2="@twitterAccount.Name"
                        parameter3="@twitterAccount.BackgroundImage"
                        parameter4="@twitterAccount.Description"
                        parameter5="@twitterAccount.FollowersCount"
                        parameter6="@twitterAccount.FollowingCount"
                        parameter7="@twitterAccount.ImageUrl"
                        parameter8="@twitterAccount.TweetsCount"
                        parameter9="@twitterAccount.UserName"
                        parameter10="@twitterAccount.IsInFavorites">
                    <i class="fa fa-user-plus">Follow</i>
                </button>
                <button class="btn unfollow-btn btn-danger" id="@unfollowBtnId" style="visibility: @visibilityUnfollow;"
                        parameter1="@twitterAccount.Id"
                        parameter2="@twitterAccount.Name"
                        parameter3="@twitterAccount.BackgroundImage"
                        parameter4="@twitterAccount.Description"
                        parameter5="@twitterAccount.FollowersCount"
                        parameter6="@twitterAccount.FollowingCount"
                        parameter7="@twitterAccount.ImageUrl"
                        parameter8="@twitterAccount.TweetsCount"
                        parameter9="@twitterAccount.UserName"
                        parameter10="@twitterAccount.IsInFavorites">
                    <i class="fa fa-user-times">Unfollow</i>
                </button>
            </div>
            <img src="@twitterAccount.ImageUrl" alt="@twitterAccount.Name Profile image" class="search-profile-pic img-circle img-thumbnail" />
            <p class="message" data-message id="@messageId"></p>
        </div>


    }
</div>

@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial");
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script>
        $(function () {
            $('.btn').click(function () {

                const data = {
                    'id': $(this).attr("parameter1"),
                    'name': $(this).attr("parameter2"),
                    'backgroundImage': $(this).attr("parameter3"),
                    'description': $(this).attr("parameter4"),
                    'followersCount': $(this).attr("parameter5"),
                    'followingCount': $(this).attr("parameter6"),
                    'imageUrl': $(this).attr("parameter7"),
                    'tweetsCount': $(this).attr("parameter8"),
                    'username': $(this).attr("parameter9"),
                    'isInFavorites': Boolean($(this).attr("parameter10"))
                };

                const buttonId = $(this).attr('id');
                console.log(buttonId);

                let postUrl;
                const messageId = `#message-${data.id}`;

                if (buttonId.startsWith('follow')) {
                    postUrl = '/twitteraccount/AddTwitterAccountToFavorites';
                }
                else {
                    postUrl = '/twitteraccount/UnfollowTwitterAccount';
                }
                console.log(postUrl);

                $.ajax({
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    url: postUrl,
                    data: JSON.stringify(data),
                    datatype: "json",
                    success: function (result) {

                        if (buttonId.startsWith('follow')) {
                            console.log('follow');
                            $(`#${buttonId}`).css('visibility', 'hidden');
                            $(`#unfollow-${data.id}`).css('visibility', 'visible');
                        }
                        else {
                            console.log('unfollow');
                            $(`#${buttonId}`).css('visibility', 'hidden');
                            $(`#follow-${data.id}`).css('visibility', 'visible');
                        }

                        $(messageId).text(result).css({ 'color': 'green', 'font-weight': '500', 'font-size': 'large' }).show().delay(3000).fadeOut();

                        $('#user-profile').load("/Home/UpdateUserProfileInLayout");
                        $('#fav-users').load("/Home/UpdateFavoriteUsersInLayout");
                    },
                    error: function (result) {
                        $(messageId).text("Error: " + result).css({ 'color': 'red', 'font-weight': '500', 'font-size': 'large' }).show().delay(3000).fadeOut();
                    }

                });
            });
        });
    </script>
}

BackUpTwitterApp/BackUpSystem.Web/Views/Shared/_TimelinePartial.cshtml
@using BackUpSystem.Web.Models.HomeViewModels
@model TimelineViewModel

<div class="body-timeline">
    @foreach (var tweet in Model.Tweets)
    {
        if (tweet.Text.StartsWith("RT"))
        {
            <p5>@tweet.TweetAuthor Retweeted</p5>
        }

        var btnId = $"btn-{tweet.Id}";
        <div id="@tweet.Id">
            <blockquote class="twitter-tweet test" id="@tweet.Id">
                <a href="@tweet.TweetUrl"></a>
            </blockquote>

            <!-- Add icon library -->
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <div class="binding-btn">
                @if (!tweet.CanBeDeleted)
                {
                    if (!tweet.IsDownloaded)
                    {
                        <button class="btn btn-click" id="@btnId"
                                parameter1="@tweet.Id"
                                parameter2="@tweet.CreatedAt"
                                parameter3="@tweet.LikesCount"
                                parameter4="@tweet.RetweetCount"
                                parameter5="@tweet.Text"
                                parameter6="@tweet.TweetAuthor"
                                parameter7="@tweet.TweetUrl">
                            <i class="fa fa-download">Download</i>
                        </button>
                    }
                }
                else
                {
                    <button class="btn btn-click" id="@btnId"
                            parameter1="@tweet.Id"
                            parameter7=@tweet.TweetUrl>
                        <i class="fa fa-trash">Delete</i>
                    </button>
                }
                <a target="_blank" asp-controller="Tweet" asp-action="Retweet" asp-route-tweetid="@tweet.Id"
                   class="btn">
                    <i class="fa fa-retweet"></i> Retweet
                </a>

            </div>
        </div>
        var messageId = $"message{tweet.Id}";
        <p class="message" data-message id="@messageId"></p>
    }
</div>

<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    $(function () {
        $(".btn-click").click(function () {
            const data = {
                'id': $(this).attr("parameter1"),
                'createdAt': $(this).attr("parameter2"),
                'likesCount': $(this).attr("parameter3"),
                'retweetsCount': $(this).attr("parameter4"),
                'text': $(this).attr("parameter5"),
                'tweetAuthor': $(this).attr("parameter6"),
                'tweetUrl': $(this).attr("parameter7")
            };

            console.log(data);
            const btnId = "#btn-" + data.id;
            const messageId = "#message" + data.id;
            let postUrl;

            if (data.createdAt != undefined) {
                postUrl = "/tweet/download";
            }
            else {
                postUrl = "/tweet/delete";
                $('#' + data.id).remove();
            }
            console.log(postUrl);
            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                url: postUrl,
                data: JSON.stringify(data),
                datatype: "json",
                success: function (result) {

                    $(btnId).hide();

                    $(messageId).text(result).css({ 'color': 'green', 'font-weight': '500', 'font-size': 'large' }).show().delay(3000).fadeOut();
                    $('#user-profile').load("/Home/UpdateUserProfileInLayout");

                },
                error: function (result) {
                    $(messageId).text("Error: " + result).css({ 'color': 'red', 'font-weight': '500', 'font-size': 'large' }).show().delay(3000).fadeOut();;
                }
            });
        });
    });
</script>

BackUpTwitterApp/BackUpSystem.Web/Views/Shared/_UserProfilePartial.cshtml
@using Microsoft.AspNetCore.Identity
@using BackUpSystem.Data.Models

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Home" asp-action="Update" method="get" id="logoutForm" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a asp-area="" asp-controller="Manage" asp-action="Index" title="Manage">Hello @UserManager.GetUserName(User)!</a>
            </li>
            <li>
                <button type="submit" class="btn btn-link navbar-btn navbar-link">Log out</button>
            </li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
        <li><a asp-area="" asp-controller="Account" asp-action="Login">Log in</a></li>
    </ul>
}