BackUpTwitterApp/BackUpSystem.Web/Areas/Admin/Models/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BackUpSystem.Web.Areas.Admin.Models
{
    public class EditViewModel
    {
        [Required]
        public string Id { get; set; }

        [Display(Name = "Name:")]
        [StringLength(40, MinimumLength = 2)]
        public string Name { get; set; }

        [Display(Name = "BirthDate:")]
        public DateTime? BirthDate { get; set; }

        [Display(Name = "ImageUrl:")]
        [MinLength(20)]
        public string UserImageUrl { get; set; }

        [Display(Name = "IsAdmin:")]
        public bool IsAdmin { get; set; }
    }
}

BackUpTwitterApp/BackUpSystem.Web/Areas/Admin/Controllers/UserManagementController.cs
using BackUpSystem.Services.Data.Contracts;
using BackUpSystem.Web.Areas.Admin.Controllers.Contracts;
using BackUpSystem.Web.Areas.Admin.Models;
using Bytes2you.Validation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BackUpSystem.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UserManagementController : Controller, IUserManagementController
    {
        private readonly IUserService userService;
        private readonly ITwitterAccountService twitterAccountService;
        private readonly ITweetService tweetService;

        public UserManagementController(
            IUserService userService,
            ITwitterAccountService twitterAccountService,
            ITweetService tweetService
            )
        {
            Guard.WhenArgument(userService, "User Service").IsNull().Throw();
            this.userService = userService;

            Guard.WhenArgument(twitterAccountService, "Twitter Account Service").IsNull().Throw();
            this.twitterAccountService = twitterAccountService;

            Guard.WhenArgument(tweetService, "Tweet Service").IsNull().Throw();
            this.tweetService = tweetService;
        }

        public async Task<IActionResult> Index()
        {

            var users = await this.userService.GetAllUsers();

            return View("Index", users);
        }

        public async Task<IActionResult> Details(string id)
        {
            var user = await this.userService.GetUserById(id);
            var twitterAccounts = await this.userService.GetAllFavoriteTwitterAccounts(id);
            var tweets = await this.userService.GetAllDownloadTweetsByUser(id);
            var detailsViewModel = new UserDetailsModel()
            {
                User = user,
                TwitterAccounts = twitterAccounts,
                Tweets = tweets
            };
            return View("Details", detailsViewModel);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var user = await this.userService.GetUserById(id);
            var viewModel = new EditViewModel
            {
                Id = user.Id,
                Name = user.Name,
                BirthDate = user.BirthDate,
                UserImageUrl = user.UserImageUrl,
                IsAdmin = user.IsAdmin
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            var user = await this.userService.GetUserById(model.Id);
            if (user == null)
            {
                return RedirectToAction("Index");
            }

            if (model.BirthDate != user.BirthDate)
            {
                await this.userService.UpdateBirthDate(model.Id, model.BirthDate);
            }

            if (model.Name != user.Name)
            {
                await this.userService.UpdateName(model.Id, model.Name);
            }

            if (model.UserImageUrl != user.UserImageUrl)
            {
                await this.userService.UpdateProfileImage(model.Id, model.UserImageUrl);
            }

            if (model.IsAdmin != user.IsAdmin)
            {
                await this.userService.UpdateIsAdmin(model.Id, model.IsAdmin);
            }

            return RedirectToAction("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete (string id)
        {
            await this.userService.DeleteUser(id);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteTwitterAccount(string userId, string twitterAccountId)
        {
            await this.twitterAccountService.DeleteTwitterAccountFromUser(userId, twitterAccountId);

            return RedirectToAction("Details", new { id = userId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>  DeleteTweet(string userId, string tweetId)
        {
            await this.tweetService.DeleteTweet(userId, tweetId);

            return RedirectToAction("Details", new { id = userId });
        }
    }
}

BackUpTwitterApp/BackUpSystem.Web/Areas/Admin/Views/UserManagement/Details.cshtml
@using BackUpSystem.Web.Areas.Admin.Models
@model UserDetailsModel

<div style="margin-left: 12%; margin-top: 3em;">
    <div> <img src="@Model.User.UserImageUrl" height="100" width="100"> </div>

    <div>
        <form asp-controller="UserManagement" asp-action="Delete" asp-route-id="@Model.User.Id" method="post">
            <input type="hidden" asp-for="@Model.User.Id" />
            <button class="btn btn-danger btn-sm" type="submit">DELETE</button>
        </form>
    </div>
    <br />
    <div>
        <a class="btn btn-info" form asp-controller="UserManagement" asp-action="Edit" asp-route-id="@Model.User.Id">EDIT</a>
    </div>

    <div>
        <table class="table table-striped">
            <tr>
                <td>User Id</td>
                <td>@Model.User.Id</td>
            </tr>
            <tr>
                <td>User Email</td>
                <td>@Model.User.Email</td>
            </tr>
            <tr>
                <td>User UserName</td>
                <td>@Model.User.UserName</td>
            </tr>
            <tr>
                <td>User Name</td>
                <td>@Model.User.Name</td>
            </tr>
            <tr>
                <td>User Joined Date</td>
                <td>@Model.User.JoinedDate</td>
            </tr>
            <tr>
                <td>User Birth Date</td>
                <td>@Model.User.BirthDate</td>
            </tr>
            <tr>
                <td>User Followed Users Count</td>
                <td>@Model.User.FollowedUsersCount</td>
            </tr>
            <tr>
                <td>User Downloaded Tweets Count</td>
                <td>@Model.User.DownloadedTweetsCount</td>
            </tr>
            <tr>
                <td>User Retweets Count</td>
                <td>@Model.User.RetweetsCount</td>
            </tr>
            <tr>
                <td>User User Image URL</td>
                <td>@Model.User.UserImageUrl</td>
            </tr>
            <tr>
                <td>User IsAdmin</td>
                <td>@Model.User.IsAdmin</td>
            </tr>
        </table>
    </div>

    <br /><br />

    <div>
        <table class="table table-striped">
            <tr>
                <th>Favorite Twitter Accounts</th>
                <th>Downloaded Tweets</th>
            </tr>
            <tr>
                <td>
                    @foreach (var account in Model.TwitterAccounts)
                    {
                        <div>
                            <form asp-controller="UserManagement" asp-action="DeleteTwitterAccount"
                                  asp-route-userId="@Model.User.Id" asp-route-twitterAccountId="@account.Id" method="post">
                                <button class="btn btn-danger btn-sm" type="submit">DELETE</button>
                            </form>
                            <b>Twitter Name:</b> @account.UserName <br />

                            <b>Tweets count:</b> @account.TweetsCount <br />

                            <b>Following count:</b> @account.FollowingCount <br />

                            <b>Followers count</b>: @account.FollowersCount <br />
                        </div>
                        <br />
                    }
                </td>
                <td>
                    @foreach (var tweet in Model.Tweets)
                    {
                        <div>
                            <form asp-controller="UserManagement" asp-action="DeleteTweet"
                                  asp-route-userId="@Model.User.Id" asp-route-tweetId="@tweet.Id" method="post">
                                <button class="btn btn-danger btn-sm" type="submit">DELETE</button>
                            </form>
                            <b>Author:</b> @tweet.TweetAuthor <br />

                            <b>Tweet content:</b> @tweet.Text <br />

                            <b>Retweet count:</b> @tweet.RetweetCount <br />
                        </div>
                        <br />
                    }
                </td>
            </tr>
        </table>
    </div>
</div>

BackUpTwitterApp/BackUpSystem.Web/Areas/Admin/Views/UserManagement/Edit.cshtml
@using BackUpSystem.Web.Areas.Admin.Models
@model EditViewModel

<form class="form-horizontal" asp-controller="UserManagement" asp-action="Edit">
    <div class="form-group">
        <label asp-for="@Model.BirthDate" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input id="birthdate" type="datetime" class="form-control" asp-for="@Model.BirthDate">
        </div>
    </div>

    <div class="form-group">
        <label asp-for="@Model.Name" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input type="text" class="form-control" asp-for="@Model.Name">
            <span class="text-danger" asp-validation-for="@Model.Name"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="@Model.UserImageUrl" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input type="text" class="form-control" asp-for="@Model.UserImageUrl">
            <span class="text-danger" asp-validation-for="@Model.UserImageUrl"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="@Model.IsAdmin" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input type="checkbox" class="form-control" asp-for="@Model.IsAdmin">
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit">EDIT</button>
        </div>
    </div>
</form>

@section Scripts{
    <script src="~/lib/jquery-ui/jquery-ui.min.js">
        
    </script>

    <script>
        $(function () {
            $('#birthdate').datepicker({
                dateFormat: $.datepicker.ISO_8601,
                maxDate: 0,
                minDate: new Date(1900, 1 - 1, 1),
                changeYear: true,
                changeMonth: true
            });
        });
    </script>
 }

BackUpTwitterApp/BackUpSystem.Web/Areas/Admin/Views/UserManagement/Index.cshtml
@using BackUpSystem.DTO
@model IEnumerable<UserDto>


@*<table class="table table-striped">
    <tr>
        <th>User:</th>
        <th>Is Admin:</th>
    </tr>
    @foreach (var user in Model)
    {
        <tr>
            <td>
                <a asp-controller="UserManagement" asp-action="Details" asp-route-id="@user.Id">@user.UserName</a>
            </td>
            <td>@user.IsAdmin</td>
        </tr>
    }

</table>*@

<div class="container">
    <div class="row">
        <div class="panel panel-primary filterable" style="margin-top: 4em !important; margin-left: 6em !important; border-color:#1da1f2;">
            <div class="panel-heading" style="background-color: #1da1f2;border-color: #1da1f2;">
                <h3 class="panel-title"><strong>User:</strong></h3>
            </div>
            <table class="table">
                <thead>
                    <tr class="filters">
                        <th><h5></h5></th>
                        <th><h5>Admin</h5></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model)
                    {
                        <tr>
                            <td>
                                <a asp-controller="UserManagement" asp-action="Details" asp-route-id="@user.Id">@user.UserName</a>
                            </td>
                            @if (@user.IsAdmin)
                            {
                                <td>
                                    <i class="fa fa-check"></i>
                                </td>
                            }
                            else
                            {
                                <td>
                                    <i class="fa fa-times"></i>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>