BackUpTwitterApp/BackUpSystem.Web/Models/HomeViewModels/TwitterAccountViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BackUpSystem.Web.Models.HomeViewModels
{
    public class TwitterAccountViewModel
    {
        public string Id { get; set; }

        [Required]
        [StringLength(30, MinimumLength = 5, ErrorMessage = "Invalid UserName format!")]
        public string UserName { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Invalid Name format!")]
        public string Name { get; set; }

        [StringLength(200, MinimumLength = 3, ErrorMessage = "Invalid Description format!")]
        public string Description { get; set; }

        public int FollowersCount { get; set; }

        public int FollowingCount { get; set; }

        public int LikesCount { get; set; }

        public int TweetsCount { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime? JoinedDate { get; set; }

        public string BackgroundImage { get; set; }

        public string ImageUrl { get; set; }

        public bool IsInFavorites { get; set; }
    }
}

BackUpTwitterApp/BackUpSystem.Web/Controllers/TwitterAccountController.cs
using BackUpSystem.Data.Models;
using BackUpSystem.DTO;
using BackUpSystem.DTO.ApiDtos;
using BackUpSystem.Services.Data.Contracts;
using BackUpSystem.Utilities.Contracts;
using BackUpSystem.Web.Models.HomeViewModels;
using Bytes2you.Validation;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace BackUpSystem.Web.Controllers
{
    public class TwitterAccountController : Controller
    {
        private readonly ITwitterService twitterService;
        private readonly ITwitterAccountService twitterAccountService;
        private readonly IUserService userService;
        private readonly IMappingProvider mappingProvider;
        private readonly UserManager<User> userManager;

        public TwitterAccountController(ITwitterService twitterService, ITwitterAccountService twitterAccountService, IUserService userService, IMappingProvider mappingProvider, UserManager<User> userManager)
        {
            Guard.WhenArgument(twitterService, "Twitter Service").IsNull().Throw();
            Guard.WhenArgument(twitterAccountService, "TwitterAccount Service").IsNull().Throw();
            Guard.WhenArgument(userService, "User Service").IsNull().Throw();
            Guard.WhenArgument(mappingProvider, "Mapping Provider").IsNull().Throw();
            Guard.WhenArgument(userManager, "User Manager").IsNull().Throw();

            this.twitterService = twitterService;
            this.twitterAccountService = twitterAccountService;
            this.userService = userService;
            this.mappingProvider = mappingProvider;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index(TwitterAccountViewModel model)
        {
            var timelineViewModel = new TimelineViewModel();
            var userTimeline = await twitterService.GetUsersTimeline(model.Id);
            Guard.WhenArgument(userTimeline, "User Timeline").IsNull().Throw();

            var twitterAccountTimeline = this.mappingProvider.ProjectTo<TweetApiDto, TweetViewModel>(userTimeline).ToList();
            var userId = this.userManager.GetUserId(this.HttpContext.User);
            var downloadedTweets = await this.userService.GetAllDownloadTweetsByUser(userId);

            foreach (var tweet in downloadedTweets)
            {
                for (int i = 0; i < twitterAccountTimeline.Count(); i++)
                {
                    if (tweet.Id == twitterAccountTimeline[i].Id)
                    {
                        twitterAccountTimeline[i].IsDownloaded = true;
                    }
                }
            }

            timelineViewModel.Tweets = twitterAccountTimeline;
            timelineViewModel.TwiitterAccountInfo = model;

            return View(timelineViewModel);
        }

        public async Task<IActionResult> AddTwitterAccountToFavorites([FromBody]TwitterAccountViewModel model)
        {
            var userId = this.userManager.GetUserId(this.HttpContext.User);

            if (model.BackgroundImage == null)
            {
                model.BackgroundImage = "https://www.smartt.com/sites/default/files/public/twitter_logo_banner_12.jpg";
            }

            var twitterAccountToaAdd = this.mappingProvider.MapTo<TwitterAccountApiDto>(model);

            await this.twitterAccountService.AddTwitterAccountToUser(twitterAccountToaAdd, userId);

            return Json($"You just followed {model.Name}!");
        }

        public async Task<IActionResult> UnfollowTwitterAccount([FromBody]TwitterAccountViewModel model)
        {
            var userId = this.userManager.GetUserId(this.HttpContext.User);

            await this.twitterAccountService.DeleteTwitterAccountFromUser(userId, model.Id);

            return Json($"{model.Name} successfully unfollowed!");
        }

        public async Task<IActionResult> DeleteTwitterAccountFromFavorites(TwitterAccountViewModel model)
        {
            var userId = this.userManager.GetUserId(this.HttpContext.User);

            await this.twitterAccountService.DeleteTwitterAccountFromUser(userId, model.Id);

            return this.RedirectToAction("Index", "Home");
        }
    }
}

BackUpTwitterApp/BackUpSystem.Web/Views/TwitterAccount/Index.cshtml
@using BackUpSystem.Web.Models.HomeViewModels
@model TimelineViewModel
<div class="container p-0 tw-acc-banner tw-acc-banner-w " >
    <div class="row m-row ">
        <div class="col-lg-12 col-lg-offset-0 col-xs-8 col-xs-offset-3 p-0 ">
            <div class="card-tw-acc hovercard">
                <div class="cardheader" style="background-image:url(@Model.TwiitterAccountInfo.BackgroundImage);">
                </div>
                <div class="avatar">
                    <img alt="" src="@Model.TwiitterAccountInfo.ImageUrl" class="img-responsive tw-acc-img ">
                </div>
                <div class="info text-white">
                    <a asp-controller="TwitterAccount" asp-action="DeleteTwitterAccountFromFavorites"
                       asp-route-id="@Model.TwiitterAccountInfo.Id"
                       class="btn unfollow-btn-details btn-danger">
                        <i class="fa fa-user-times"></i> Unfollow
                    </a>
                    <div class="title">
                        <p class="text-white">@Model.TwiitterAccountInfo.Name</p>
                    </div>
                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2">
                            <p>@Model.TwiitterAccountInfo.Description</p><hr />
                        </div>
                        <div class="col-lg-4 col-lg-offset-0  col-md-offset-0 col-xs-3 col-xs-offset-1 p-0">
                            <p>Followers:</p>
                            <p>@Model.TwiitterAccountInfo.FollowersCount</p>
                        </div>
                        <div class="col-lg-4 col-xs-3 p-0">
                            <p>Following</p>
                            <p>@Model.TwiitterAccountInfo.FollowingCount</p>
                        </div>
                        <div class="col-lg-4 col-xs-3 p-0">
                            <p>Tweets</p>
                            <p> @Model.TwiitterAccountInfo.TweetsCount</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@if (Model.Tweets.Any())
{
    <div class="col-lg-8 col-lg-offset-3 col-xs-10 col-xs-offset-2">
        @Html.Partial("_TimelinePartial", Model)
    </div>
}
else
{
    <p2>@Model.TwiitterAccountInfo.Name has no posts yet...!</p2>
}